# Generated by Django 5.2.1 on 2025-05-23 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitCoreBack', '0002_clientreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='class_type',
            field=models.CharField(blank=True, choices=[('step', 'Step'), ('bodypump', 'Bodypump'), ('spinning', 'Spinning'), ('zumba', 'Zumba'), ('crossfit', 'Crossfit'), ('pilates', 'Pilates'), ('yoga', 'Yoga')], max_length=20, null=True, verbose_name='Tipo de clase'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_profesional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
