# Generated by Django 5.2.1 on 2025-05-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitCoreBack', '0003_alter_appointment_class_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('professional', 'datetime'), name='unique_professional_time'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'clase')), fields=('class_type', 'datetime'), name='unique_class_time'),
        ),
    ]
