# Generated by Django 5.2.1 on 2025-05-26 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitCoreBack', '0006_evolutiondata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evolutiondata',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='evolutiondata',
            name='muscle_mass',
            field=models.FloatField(help_text='Masa muscular en porcentaje'),
        ),
        migrations.AlterField(
            model_name='evolutiondata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evolutiondata',
            name='weight',
            field=models.FloatField(help_text='Peso en kilogramos'),
        ),
    ]
